#%RAML 0.8

title: Generic API
baseUri: http://ApiServer/
/:
  displayName: Homepage
  description: Should return standard greeting
  get:
    responses:
      200:
        body:
          text/html:
            example: |
              Hello, world!
/ping:
  displayName: Ping endpoint
  description: Should respond to standard ping
  get:
    responses:
      200:
        body:
          text/html:
            example: |
              Pong
/reflection:
  displayName: Json reflection
  description: Should return identical Json in response as provided by request
  post:
    body:
      application/json:
        schema: |
          { "greeting": "Hello, world!" }
    responses:
      200:
        body:
          application/json:
            schema: |
              { "greeting": "Hello, world!" }
/posts:
  displayName: Post creation endpoint
  description: Should return the new post's id
  post:
    body:
      application/json:
        schema: |
          { "body": "Hello, world!" }
    responses:
      200:
        body:
          application/json:
            schema: |
              { "id": 1 }
/post/{id}:
  displayName: Post endpoint
  get:
    description: Should return a post
    responses:
      200:
        body:
          application/json:
            schema: |
              { "id": 1, "body": "Hello, world!" }
  delete:
    description: Should delete a post
  put:
    description: Should update a post
    body:
      application/json:
        schema: |
          { "body": "Jello, world!" }
    responses:
      200:
        body:
          application/json:
            schema: |
              { "id": 1, "body": "Hello, world!" }
