sudo: required
language: go
go:
  - 1.5
services:
  - docker

before_script:
  - go vet github.com/ihsw/the-matrix/app/...
  - ./bin/build-images
script:
  - go test -v github.com/ihsw/the-matrix/app/...
