sudo: required
language: go
go:
  - 1.8
services:
  - docker

env:
  global:
  - APP_PATH=github.com/ihsw/the-matrix/app
install:
- go get -t $APP_PATH/...
- go get github.com/mattn/goveralls
script:
- $GOPATH/bin/goveralls -package github.com/galactic-filament/the-matrix/app/... -service=travis-ci
