sudo: required
language: go
go:
  - 1.5
services:
  - docker

env:
  - ENV=travis
before_script:
  - go vet github.com/ihsw/the-matrix/app/...
  - docker build -t ihsw/the-matrix-db ./db
script:
  - go test -v github.com/ihsw/the-matrix/app/...
