test-suite-base:
  image: ihsw/the-matrix
  command: go test -v github.com/ihsw/the-matrix/app/...
test-suite:
  extends:
    service: test-suite-base
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
test-suite-dev:
  extends:
    service: test-suite-base
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./app:/go/src/github.com/ihsw/the-matrix/app
