base:
  image: ihsw/the-matrix
test-suite:
  extends:
    service: base
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
test-suite-dev:
  extends:
    service: test-suite
  volumes:
    - ./app:/srv/app

base-raml-viewer:
  image: ihsw/the-matrix-raml-viewer
raml-viewer:
  extends:
    service: base-raml-viewer
  ports:
    - 80:80
raml-viewer-dev:
  extends:
    service: raml-viewer
  volumes:
    - ./raml-viewer/app:/srv/app

tests:
  image: ihsw/the-matrix-tests
