test-suite-base:
  image: ihsw/the-matrix
  environment:
    - ENV=local
  command: go test -v github.com/ihsw/the-matrix/app/...

test-suite:
  extends:
    service: test-suite-base
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
