#%RAML 0.8

title: Generic API
baseUri: http://localhost/
/:
  displayName: Homepage
  get:
    description: |
      Just responds with 'Hello, world!'
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "greeting": "Hello, world!"
              }
