#%RAML 0.8

title: Generic API
baseUri: http://ApiServer/
/:
  displayName: Homepage
  description: Should return standard greeting
  get:
    responses:
      200:
        body:
          text/html:
            example: |
              Hello, world!
/ping:
  displayName: Ping endpoint
  description: Should respond to standard ping
  get:
    responses:
      200:
        body:
          text/html:
            example: |
              Pong
